## 簡介
除了python 原生的 dict, array之外, 介紹各類型Data Structure在 numpy, pandas 的使用狀況

In [2]:
import numpy as np
import matplotlib as mp
import pandas as pd
%matplotlib inline
import sklearn
import os
import sys

In [6]:
a= np.pi
b = np.array([2.7,np.pi])
c = np.array(["a","b"],dtype = np.str)

In [41]:
np.array([1,"1"])

array(['1', '1'],
      dtype='<U21')

### [factor](https://stackoverflow.com/questions/34682420/python-how-to-convert-a-string-array-to-a-factor-list)


In [12]:
classes = np.array(['a', 'b', 'c', 'c', 'b', 'a', 'a', 'd'])
classnames, indices = np.unique(classes, return_inverse=True)
print(classnames)
print(indices)
print(classnames[indices])

['a' 'b' 'c' 'd']
[0 1 2 2 1 0 0 3]
['a' 'b' 'c' 'c' 'b' 'a' 'a' 'd']


## List

In [31]:
d = {"A":"a","B": 1}
pd.Series(d)

A    a
B    1
dtype: object

## DataFrame

In [32]:
pd.DataFrame(data = {"x":np.arange(3),"y":["2"]*3})

x  y
0  0  2
1  1  2
2  2  2

## [Date](https://docs.scipy.org/doc/numpy-1.12.0/reference/arrays.datetime.html)

In [34]:
np.array(['2007-07-13', '2006-01-13', '2010-08-13'], dtype='datetime64')

array(['2007-07-13', '2006-01-13', '2010-08-13'], dtype='datetime64[D]')

In [35]:
np.datetime64('2009-01-01') - np.datetime64('2008-01-01')

numpy.timedelta64(366,'D')

## [Matrix](https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.matrix.html)

In [36]:
np.matrix('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

In [37]:
 np.matrix([[1, 2], [3, 4]])

matrix([[1, 2],
        [3, 4]])

In [40]:

np.matrix(np.arange(12).reshape((3,4)))

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

## 4.1 附加資料到向量

In [42]:
a = np.array([1,2,3])

In [46]:
np.append(a,1)

array([1, 2, 3, 1])

In [47]:
np.append(a,[3,4])

array([1, 2, 3, 3, 4])

## 4.2 將資料插入向量
請參考 [np.insert](https://docs.scipy.org/doc/numpy/reference/generated/numpy.insert.html#numpy.insert)

In [50]:
np.insert(a,1,5)

array([1, 5, 2, 3])

## 4.3 循環規則
Python 沒有這個性質

## 4.4 產生因子
 - enumerate
 - [numpy.ndenumerate](https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.ndenumerate.html) 

目前還沒有看見更好的解法
有接近的[解法](https://stackoverflow.com/questions/15124439/closest-equivalent-of-a-factor-variable-in-python-pandas)

In [52]:
b = np.array([[1, 2], [3, 4]])
np.ndenumerate(b)

In [62]:
s = pd.Series(["a","b","c","a"], dtype="category")
s

0    a
1    b
2    c
3    a
dtype: category
Categories (3, object): [a, b, c]

## 4.5 合併多向量成為單一向量與對應因子

In [68]:
data = {"a":[1,2],"b":['abc','zxy']}
pd.DataFrame(pd.DataFrame(data).stack())

0
0 a    1
  b  abc
1 a    2
  b  zxy

## 4.6 建立list


In [72]:
a = pd.Series({"a":1,"b":"3sdf","c":np.mean})

In [73]:
a["a"]

1

In [76]:
a["c"]([1,2])

1.5

## 4.7 選取list中的元素
- index
- name


In [77]:
a[0]

1

In [78]:
a[1]

'3sdf'

In [79]:
a[2]

<function numpy.core.fromnumeric.mean>

In [100]:
df = pd.DataFrame(data = a).T
df.index = ["1asdf"]
df

a     b                               c
1asdf  1  3sdf  <function mean at 0x10ac18e18>

In [101]:
#https://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-integer
df.iloc[0,:2] # 用row index

a       1
b    3sdf
Name: 1asdf, dtype: object

## 5.8 用名稱選取列表元素

In [104]:
df.loc["1asdf",:] #用row name

a                                 1
b                              3sdf
c    <function mean at 0x10ac18e18>
Name: 1asdf, dtype: object

## 5.9 建立一個key-value list

In [105]:
pd.Series({"a":31312,"b":["GG"]})

a    31312
b     [GG]
dtype: object

## 5.10 從列表中移出元素
可以參考[pd.drop](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.drop.html) 或者是[範例](https://stackoverflow.com/questions/14661701/how-to-drop-a-list-of-rows-from-pandas-dataframe)

## 5.11 將列表轉換為向量


In [107]:
df.values

array([[1, '3sdf', <function mean at 0x10ac18e18>]], dtype=object)

## 5.12 移除列表中na值

In [110]:
a = pd.DataFrame(data = [[1,np.NaN],[2,2]])
a

In [112]:
a.dropna()

0    1
1  2  2.0

## 5.13 條件式移除列表元素

In [117]:
a = pd.DataFrame(data = [np.zeros(9),np.arange(9)+2,np.linspace(100,108,9)])

In [118]:
a

0      1      2      3      4      5      6      7      8
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
1    2.0    3.0    4.0    5.0    6.0    7.0    8.0    9.0   10.0
2  100.0  101.0  102.0  103.0  104.0  105.0  106.0  107.0  108.0

In [121]:
a == 0 

0      1      2      3      4      5      6      7      8
0   True   True   True   True   True   True   True   True   True
1  False  False  False  False  False  False  False  False  False
2  False  False  False  False  False  False  False  False  False

In [122]:
a [ a > 5 ]

0      1      2      3      4      5      6      7      8
0    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
1    NaN    NaN    NaN    NaN    6.0    7.0    8.0    9.0   10.0
2  100.0  101.0  102.0  103.0  104.0  105.0  106.0  107.0  108.0

In [123]:
a [ a > 5 ] = -1

In [124]:
a

0    1    2    3    4    5    6    7    8
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  2.0  3.0  4.0  5.0 -1.0 -1.0 -1.0 -1.0 -1.0
2 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0