20181116

# 研究函數

In [3]:
import numpy as np

In [1]:
def softmax_wrong(x):
    c = np.max(x)
    exp_a = np.exp(x-c) #防止溢位
    sum_exp_a = np.sum(exp_a)
    return exp_a / sum_exp_a

In [4]:
x = np.array([[1,2],[3,4]])

In [17]:
softmax_wrong(x)

array([[0.0320586 , 0.08714432],
       [0.23688282, 0.64391426]])

In [6]:
np.sum(softmax_wrong(x))

1.0

In [7]:
def softmax(x):
    if x.ndim == 2:
        x = x.T
        x = x - np.max(x, axis=0)
        y = np.exp(x) / np.sum(np.exp(x), axis=0)
        return y.T 

    x = x - np.max(x) 
    return np.exp(x) / np.sum(np.exp(x))

In [11]:
softmax(x)

array([[0.26894142, 0.73105858],
       [0.26894142, 0.73105858]])

In [15]:
x.T 

array([[1, 3],
       [2, 4]])

TypeError: softmax() got an unexpected keyword argument 'axis'